#!/usr/bin/env zsh

set -euo pipefail

MODEL_NAME="${MLX_BASE_MODEL_NAME:-lmstudio-community/LFM2-24B-A2B-MLX-4bit}"
HOST="${MLX_BASE_SERVER_HOST:-0.0.0.0}"
PORT="${MLX_BASE_SERVER_PORT:-1235}"
LOG_LEVEL="${MLX_BASE_SERVER_LOG_LEVEL:-INFO}"
TRUST_REMOTE_CODE="${MLX_BASE_SERVER_TRUST_REMOTE_CODE:-0}"
TEMP="${MLX_BASE_SERVER_TEMP:-}"
TOP_P="${MLX_BASE_SERVER_TOP_P:-}"
TOP_K="${MLX_BASE_SERVER_TOP_K:-}"
MIN_P="${MLX_BASE_SERVER_MIN_P:-}"
MAX_TOKENS="${MLX_BASE_SERVER_MAX_TOKENS:-}"
DECODE_CONCURRENCY="${MLX_BASE_SERVER_DECODE_CONCURRENCY:-}"
PROMPT_CONCURRENCY="${MLX_BASE_SERVER_PROMPT_CONCURRENCY:-}"
PREFILL_STEP_SIZE="${MLX_BASE_SERVER_PREFILL_STEP_SIZE:-}"
PROMPT_CACHE_SIZE="${MLX_BASE_SERVER_PROMPT_CACHE_SIZE:-}"
PROMPT_CACHE_BYTES="${MLX_BASE_SERVER_PROMPT_CACHE_BYTES:-}"
CHAT_TEMPLATE_ARGS="${MLX_BASE_SERVER_CHAT_TEMPLATE_ARGS:-}"
AI_STORAGE_ROOT="${AI_STORAGE_ROOT:-/Volumes/ExtData/ai-assistant}"
MLX_CACHE_ROOT="${MLX_CACHE_ROOT:-$AI_STORAGE_ROOT/mlx}"
HF_HOME="${HF_HOME:-$MLX_CACHE_ROOT/huggingface}"
HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
LMSTUDIO_HOME="${LMSTUDIO_HOME:-$MLX_CACHE_ROOT/lmstudio}"

mkdir -p "$HF_HOME" "$HUGGINGFACE_HUB_CACHE" "$TRANSFORMERS_CACHE" "$LMSTUDIO_HOME"

export AI_STORAGE_ROOT
export MLX_CACHE_ROOT
export HF_HOME
export HUGGINGFACE_HUB_CACHE
export TRANSFORMERS_CACHE
export LMSTUDIO_HOME

typeset -a SERVER_ARGS

SERVER_ARGS=(
  --model "$MODEL_NAME"
  --host "$HOST"
  --port "$PORT"
  --log-level "$LOG_LEVEL"
)

[[ "$TRUST_REMOTE_CODE" == "1" ]] && SERVER_ARGS+=(--trust-remote-code)
[[ -n "$TEMP" ]] && SERVER_ARGS+=(--temp "$TEMP")
[[ -n "$TOP_P" ]] && SERVER_ARGS+=(--top-p "$TOP_P")
[[ -n "$TOP_K" ]] && SERVER_ARGS+=(--top-k "$TOP_K")
[[ -n "$MIN_P" ]] && SERVER_ARGS+=(--min-p "$MIN_P")
[[ -n "$MAX_TOKENS" ]] && SERVER_ARGS+=(--max-tokens "$MAX_TOKENS")
[[ -n "$DECODE_CONCURRENCY" ]] && SERVER_ARGS+=(--decode-concurrency "$DECODE_CONCURRENCY")
[[ -n "$PROMPT_CONCURRENCY" ]] && SERVER_ARGS+=(--prompt-concurrency "$PROMPT_CONCURRENCY")
[[ -n "$PREFILL_STEP_SIZE" ]] && SERVER_ARGS+=(--prefill-step-size "$PREFILL_STEP_SIZE")
[[ -n "$PROMPT_CACHE_SIZE" ]] && SERVER_ARGS+=(--prompt-cache-size "$PROMPT_CACHE_SIZE")
[[ -n "$PROMPT_CACHE_BYTES" ]] && SERVER_ARGS+=(--prompt-cache-bytes "$PROMPT_CACHE_BYTES")
[[ -n "$CHAT_TEMPLATE_ARGS" ]] && SERVER_ARGS+=(--chat-template-args "$CHAT_TEMPLATE_ARGS")

exec "$HOME/.local/bin/mlx_lm.server" "${SERVER_ARGS[@]}"