#!/usr/bin/env zsh

set -euo pipefail

MODEL_NAME="${MLX_BASE_MODEL_NAME:-lmstudio-community/LFM2-24B-A2B-MLX-4bit}"
HOST="${MLX_BASE_SERVER_HOST:-0.0.0.0}"
PORT="${MLX_BASE_SERVER_PORT:-1235}"
LOG_LEVEL="${MLX_BASE_SERVER_LOG_LEVEL:-INFO}"
AI_STORAGE_ROOT="${AI_STORAGE_ROOT:-/Volumes/ExtData/ai-assistant}"
MLX_CACHE_ROOT="${MLX_CACHE_ROOT:-$AI_STORAGE_ROOT/mlx}"
HF_HOME="${HF_HOME:-$MLX_CACHE_ROOT/huggingface}"
HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
LMSTUDIO_HOME="${LMSTUDIO_HOME:-$MLX_CACHE_ROOT/lmstudio}"

mkdir -p "$HF_HOME" "$HUGGINGFACE_HUB_CACHE" "$TRANSFORMERS_CACHE" "$LMSTUDIO_HOME"

export AI_STORAGE_ROOT
export MLX_CACHE_ROOT
export HF_HOME
export HUGGINGFACE_HUB_CACHE
export TRANSFORMERS_CACHE
export LMSTUDIO_HOME

exec "$HOME/.local/bin/mlx_lm.server" \
  --model "$MODEL_NAME" \
  --host "$HOST" \
  --port "$PORT" \
  --log-level "$LOG_LEVEL"